CREATE TABLE IF NOT EXISTS t_staff (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    login_name VARCHAR(255),
    password VARCHAR(255),
    year_entry VARCHAR(255),
    year_separation VARCHAR(255),
    company_id INT,
    dept_id VARCHAR(255),
    position_id VARCHAR(255),
    sex BIT,
    birthday DATE,
    mobile VARCHAR(255),
    education VARCHAR(255),
    nation VARCHAR(255),
    marital BIT,
    household VARCHAR(255),
    profession VARCHAR(255),
    address VARCHAR(255),
    email VARCHAR(255),
    id_card VARCHAR(255),
    status BIT,
    create_time TIMESTAMP,
    creator INT,
    modify_time TIMESTAMP,
    modificator INT,
    enabled INT,
    locked INT,
    resume LONGTEXT,
    evaluation LONGTEXT,
    follow VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS t_menu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pid VARCHAR(255),
    name VARCHAR(255),
    url VARCHAR(255),
    target VARCHAR(255),
    relative BIT,
    icon VARCHAR(255),
    seq INT,
    enable BIT,
    visible BIT
);
